spring.application.name=backend
server.port=${SPRINGBOOT_PORT:8081}
spring.datasource.url=${SUPABASE_DB_URL:jdbc:h2:mem:eatrading;DB_CLOSE_DELAY=-1}
spring.datasource.username=${SUPABASE_DB_USER:sa}
spring.datasource.password=${SUPABASE_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
